[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.20.1"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.2"

[[constraint]]
  name = "go.mongodb.org/mongo-driver"
  version = "1.0.1"

[prune]
  go-tests = true
  unused-packages = true
