version: "2"

services:
  address-service-mongodb:
    image: "mongo:3.7-jessie"
    ports :
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=address_service_adm
      - MONGO_INITDB_ROOT_PASSWORD=address_service_pwd
    command: --auth